#!/bin/bash
#Update dan Upgrade berdasarkan penjadwalan lalu ditampilkan apa yang sudah diupdate

apt-get install unattended-upgrades
dpkg-reconfigure unattended-upgrades

if apt-get upgrade -y; then
    echo "$(date): Update Anda berhasil" >> hasil.txt
        cat /var/log/apt/history.log >> hasil.txt
else
    echo "$(date): Update Anda gagal" >> hasil.txt
        cat /var/log/apt/history.log >> hasil.txt
fi




