#!/bin/bash
#Update dan Upgrade berdasarkan penjadwalan lalu ditampilkan apa yang sudah diupdate

disk1=$(df -h)
echo "Selamat datang di program Upgrade Otomatis"
echo "Disk Usage sebelum Update:"
echo "$disk1"
sleep 3
info=`slackpkg list --upgradable`

#Menampilkan daftar software yang upgradable
echo "Daftar Software yang perlu diupdate"
for x in $info;
        do echo $x;
done

sleep 3
if [ $(id -u) = 0 ];then #pengecekan user root
echo "Silahkan memilih mirrors terlebih dahulu!"
sleep 3
nano /etc/slackpkg/mirrors #memilih mirror
echo -n "Apakah Anda yakin (y/n)?"
read answer
while echo "$answer" | grep -iq "^n"
        do
        nano /etc/slackpkg/mirrors
        echo -n "Apakah Anda yakin (y/n) ?"
        read answer
done

while echo "$answer" | grep -iq "^y"
        do
        slackpkg update gpg
        slackpkg update
        slackpkg install-new
        slackpkg upgrade-all

echo "$(date): Upgrade Anda berhasil" >> hasil.txt
cat /var/log/packages/* >> hasil.txt

echo "Disk Usage sesudah di Update : "
echo "$disk1"
done
fi
